name: Validate

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ "main" ]
    types:
      - synchronize
      - opened
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: pip install check-jsonschema

      - name: Validate package collector configuration
        run: |
          cd aptrepo/collector
          check-jsonschema --schemafile schema/release-config.schema.json config/release-config.json

      - name: Validate repository adder script
        run: |
          cd aptrepo/repository
          sudo ./add_repo.sh
